export default {
  FIREBASE: 'https://gsflunchnlearn.firebaseio.com/',

  // TOPIC ACTIONS
	ADD_TOPIC: 'ADD_TOPIC',
  DELETE_TOPIC: 'DELETE_TOPIC',
	ASSIGN_TOPIC: 'ASSIGN_TOPIC',
  UNASSIGN_TOPIC: 'UNASSIGN_TOPIC',
  RECEIVE_TOPICS_DATA: 'RECEIVE_TOPICS_DATA',
  ASSIGN_DATE: 'ASSIGN_DATE',
  UNASSIGN_DATE: 'UNASSIGN_DATE',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',

  // AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

  //CURRENT TOPIC ACTIONS
  SET_CURRENT_TOPIC: 'SET_CURRENT_TOPIC'
};
